[features]
resolution = true
skip-lint = false

[programs.localnet]
droog_game = "H5zERNABU2sbbPPaCzYdVabNmAzSWm9eX8PJr2fekncB"

[programs.devnet]
droog_game = "H5zERNABU2sbbPPaCzYdVabNmAzSWm9eX8PJr2fekncB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator]
geyser_plugin_config = "tests/geyser-plugin-config.json"

[[test.validator.account]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
filename = "tests/bin/spl_token-3.5.0.so"

[[test.validator.account]]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
filename = "tests/bin/spl_token_2022-0.6.0.so"
