[features]
resolution = true
skip-lint = false

[programs.localnet]
droog_game = "DroogGame1111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[test.validator.clone]
geyser_plugin_config = "tests/geyser-plugin-config.json"

[test.validator.account]
[test.validator.account."spl_token"]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
executable = "tests/bin/spl_token-3.5.0.so"
[test.validator.account."spl_token-2022"]
address = "TokenzQdBNbLqP5VEhdkAS6EPFLC1PHnBqCXEpPxuEb"
executable = "tests/bin/spl_token_2022-0.6.0.so"

[build]
[build.rust]
features = ["no-entrypoint", "no-idl", "no-log-ix-name"]
